-- ScoutHub v1 — fresh database schema
-- Jalankan pada project Supabase baru melalui SQL Editor.
-- Skema ini tidak menghapus tabel yang sudah ada. Untuk migrasi database lama,
-- buat backup lalu sesuaikan nama/kolom sebelum menjalankan berkas ini.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text,
  phone text,
  role text not null default 'pembina' check (role in ('pembina', 'admin')),
  avatar_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.gudep (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  school_name text not null,
  gudep_number text,
  address text,
  level text not null default 'Penggalang',
  academic_year text not null default '2026/2027',
  is_active boolean not null default true,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.members (
  id uuid primary key default gen_random_uuid(),
  gudep_id uuid not null references public.gudep(id) on delete cascade,
  name text not null,
  student_number text,
  nisn text,
  gender text not null check (gender in ('L', 'P')),
  class_name text not null,
  scout_level text not null default 'Penggalang Ramu',
  parent_phone text,
  status text not null default 'Aktif' check (status in ('Aktif', 'Cuti', 'Alumni')),
  notes text,
  joined_at date not null default current_date,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.patrols (
  id uuid primary key default gen_random_uuid(),
  gudep_id uuid not null references public.gudep(id) on delete cascade,
  name text not null,
  patrol_type text not null default 'Putra' check (patrol_type in ('Putra', 'Putri')),
  leader_member_id uuid references public.members(id) on delete set null,
  vice_leader_member_id uuid references public.members(id) on delete set null,
  color text not null default '#10b981',
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique(gudep_id, name)
);

alter table public.members add column if not exists patrol_id uuid references public.patrols(id) on delete set null;

create table if not exists public.training_sessions (
  id uuid primary key default gen_random_uuid(),
  gudep_id uuid not null references public.gudep(id) on delete cascade,
  title text not null,
  training_date date not null,
  start_time time not null default '14:00',
  end_time time,
  location text not null default 'Pangkalan',
  material text,
  objective text,
  description text,
  evaluation_notes text,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.attendance (
  id uuid primary key default gen_random_uuid(),
  training_session_id uuid not null references public.training_sessions(id) on delete cascade,
  member_id uuid not null references public.members(id) on delete cascade,
  status text not null default 'Hadir' check (status in ('Hadir', 'Izin', 'Sakit', 'Alpa')),
  note text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique(training_session_id, member_id)
);

create table if not exists public.sku_items (
  id bigint generated by default as identity primary key,
  level text not null,
  category text not null default 'Umum',
  item_number integer not null,
  title text not null,
  description text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  unique(level, item_number)
);

create table if not exists public.member_sku_progress (
  id uuid primary key default gen_random_uuid(),
  member_id uuid not null references public.members(id) on delete cascade,
  sku_item_id bigint not null references public.sku_items(id) on delete cascade,
  status text not null default 'Belum' check (status in ('Belum', 'Proses', 'Lulus')),
  note text,
  validated_by uuid references auth.users(id) on delete set null,
  validated_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique(member_id, sku_item_id)
);

create table if not exists public.skk_items (
  id bigint generated by default as identity primary key,
  field_number integer not null check (field_number between 1 and 5),
  field_name text not null,
  item_number integer not null,
  name text not null,
  source_reference text not null default 'Kwarnas Gerakan Pramuka Nomor 132 Tahun 1979',
  created_at timestamptz not null default timezone('utc', now()),
  unique(field_number, item_number)
);

create table if not exists public.skk_requirements (
  id bigint generated by default as identity primary key,
  skk_item_id bigint not null references public.skk_items(id) on delete cascade,
  level text not null check (level in ('Purwa', 'Madya', 'Utama')),
  description text not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique(skk_item_id, level)
);

create table if not exists public.member_skk_progress (
  id uuid primary key default gen_random_uuid(),
  member_id uuid not null references public.members(id) on delete cascade,
  skk_item_id bigint not null references public.skk_items(id) on delete cascade,
  level text not null check (level in ('Purwa', 'Madya', 'Utama')),
  status text not null default 'Belum' check (status in ('Belum', 'Proses', 'Lulus')),
  note text,
  validated_by uuid references auth.users(id) on delete set null,
  validated_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique(member_id, skk_item_id, level)
);

create or replace function public.validate_scouthub_relations()
returns trigger language plpgsql set search_path = public as $$
declare
  related_gudep uuid;
  session_gudep uuid;
  member_gudep uuid;
begin
  if tg_table_name = 'members' and new.patrol_id is not null then
    select gudep_id into related_gudep from public.patrols where id = new.patrol_id;
    if related_gudep is distinct from new.gudep_id then raise exception 'Regu dan anggota harus berasal dari gudep yang sama'; end if;
  elsif tg_table_name = 'patrols' then
    if new.leader_member_id is not null then
      select gudep_id into related_gudep from public.members where id = new.leader_member_id;
      if related_gudep is distinct from new.gudep_id then raise exception 'Pemimpin regu harus berasal dari gudep yang sama'; end if;
    end if;
    if new.vice_leader_member_id is not null then
      select gudep_id into related_gudep from public.members where id = new.vice_leader_member_id;
      if related_gudep is distinct from new.gudep_id then raise exception 'Wakil pemimpin harus berasal dari gudep yang sama'; end if;
    end if;
  elsif tg_table_name = 'attendance' then
    select gudep_id into session_gudep from public.training_sessions where id = new.training_session_id;
    select gudep_id into member_gudep from public.members where id = new.member_id;
    if session_gudep is distinct from member_gudep then raise exception 'Pertemuan dan anggota harus berasal dari gudep yang sama'; end if;
  end if;
  return new;
end;
$$;

create index if not exists idx_gudep_created_by on public.gudep(created_by);
create index if not exists idx_members_gudep on public.members(gudep_id);
create index if not exists idx_members_patrol on public.members(patrol_id);
create index if not exists idx_patrols_gudep on public.patrols(gudep_id);
create index if not exists idx_training_gudep_date on public.training_sessions(gudep_id, training_date);
create index if not exists idx_attendance_session on public.attendance(training_session_id);
create index if not exists idx_attendance_member on public.attendance(member_id);
create index if not exists idx_sku_progress_member on public.member_sku_progress(member_id);
create index if not exists idx_skk_items_field on public.skk_items(field_number, item_number);
create index if not exists idx_skk_requirements_item on public.skk_requirements(skk_item_id, level);
create index if not exists idx_skk_progress_member on public.member_skk_progress(member_id);

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists gudep_updated_at on public.gudep;
create trigger gudep_updated_at before update on public.gudep for each row execute function public.set_updated_at();
drop trigger if exists members_updated_at on public.members;
create trigger members_updated_at before update on public.members for each row execute function public.set_updated_at();
drop trigger if exists patrols_updated_at on public.patrols;
create trigger patrols_updated_at before update on public.patrols for each row execute function public.set_updated_at();
drop trigger if exists training_updated_at on public.training_sessions;
create trigger training_updated_at before update on public.training_sessions for each row execute function public.set_updated_at();
drop trigger if exists attendance_updated_at on public.attendance;
create trigger attendance_updated_at before update on public.attendance for each row execute function public.set_updated_at();
drop trigger if exists sku_progress_updated_at on public.member_sku_progress;
create trigger sku_progress_updated_at before update on public.member_sku_progress for each row execute function public.set_updated_at();
drop trigger if exists skk_progress_updated_at on public.member_skk_progress;
create trigger skk_progress_updated_at before update on public.member_skk_progress for each row execute function public.set_updated_at();
drop trigger if exists members_validate_relation on public.members;
create trigger members_validate_relation before insert or update of patrol_id, gudep_id on public.members for each row execute function public.validate_scouthub_relations();
drop trigger if exists patrols_validate_relation on public.patrols;
create trigger patrols_validate_relation before insert or update of leader_member_id, vice_leader_member_id, gudep_id on public.patrols for each row execute function public.validate_scouthub_relations();
drop trigger if exists attendance_validate_relation on public.attendance;
create trigger attendance_validate_relation before insert or update of training_session_id, member_id on public.attendance for each row execute function public.validate_scouthub_relations();

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, email)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''), new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.owns_gudep(target_gudep uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.gudep where id = target_gudep and created_by = auth.uid());
$$;

alter table public.profiles enable row level security;
alter table public.gudep enable row level security;
alter table public.members enable row level security;
alter table public.patrols enable row level security;
alter table public.training_sessions enable row level security;
alter table public.attendance enable row level security;
alter table public.sku_items enable row level security;
alter table public.member_sku_progress enable row level security;
alter table public.skk_items enable row level security;
alter table public.skk_requirements enable row level security;
alter table public.member_skk_progress enable row level security;

drop policy if exists "profiles own row" on public.profiles;
create policy "profiles own row" on public.profiles for all to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "owners manage gudep" on public.gudep;
create policy "owners manage gudep" on public.gudep for all to authenticated using (created_by = auth.uid()) with check (created_by = auth.uid());

drop policy if exists "owners manage members" on public.members;
create policy "owners manage members" on public.members for all to authenticated using (public.owns_gudep(gudep_id)) with check (public.owns_gudep(gudep_id));

drop policy if exists "owners manage patrols" on public.patrols;
create policy "owners manage patrols" on public.patrols for all to authenticated using (public.owns_gudep(gudep_id)) with check (public.owns_gudep(gudep_id));

drop policy if exists "owners manage training" on public.training_sessions;
create policy "owners manage training" on public.training_sessions for all to authenticated using (public.owns_gudep(gudep_id)) with check (public.owns_gudep(gudep_id) and created_by = auth.uid());

drop policy if exists "owners manage attendance" on public.attendance;
create policy "owners manage attendance" on public.attendance for all to authenticated
using (exists(select 1 from public.training_sessions session where session.id = training_session_id and public.owns_gudep(session.gudep_id)))
with check (
  exists(select 1 from public.training_sessions session where session.id = training_session_id and public.owns_gudep(session.gudep_id))
  and exists(select 1 from public.members member where member.id = member_id and public.owns_gudep(member.gudep_id))
);

drop policy if exists "authenticated read sku items" on public.sku_items;
create policy "authenticated read sku items" on public.sku_items for select to authenticated using (true);

drop policy if exists "owners manage sku progress" on public.member_sku_progress;
create policy "owners manage sku progress" on public.member_sku_progress for all to authenticated
using (exists(select 1 from public.members member where member.id = member_id and public.owns_gudep(member.gudep_id)))
with check (exists(select 1 from public.members member where member.id = member_id and public.owns_gudep(member.gudep_id)));

drop policy if exists "authenticated read skk items" on public.skk_items;
create policy "authenticated read skk items" on public.skk_items for select to authenticated using (true);

drop policy if exists "authenticated read skk requirements" on public.skk_requirements;
create policy "authenticated read skk requirements" on public.skk_requirements for select to authenticated using (true);

drop policy if exists "owners manage skk progress" on public.member_skk_progress;
create policy "owners manage skk progress" on public.member_skk_progress for all to authenticated
using (exists(select 1 from public.members member where member.id = member_id and public.owns_gudep(member.gudep_id)))
with check (exists(select 1 from public.members member where member.id = member_id and public.owns_gudep(member.gudep_id)));

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.profiles, public.gudep, public.members, public.patrols, public.training_sessions, public.attendance, public.member_sku_progress, public.member_skk_progress to authenticated;
grant select on public.sku_items, public.skk_items, public.skk_requirements to authenticated;
grant usage, select on all sequences in schema public to authenticated;
