-- Materi resmi SKU Penggalang dari Panduan Penyelesaian SKU Pramuka
-- Golongan Penggalang, Keputusan Kwarnas Nomor 198 dan 199 Tahun 2011.
-- Kolom description memuat keterangan tambahan ketika butir memiliki rincian.

insert into public.sku_items (level, category, item_number, title, description) values
('Penggalang Ramu', 'Spiritual', 1, 'Selalu taat menjalankan ibadah agamanya secara pribadi ataupun berjamaah', ''),
('Penggalang Ramu', 'Spiritual', 2, 'Dapat mengetahui dan menjelaskan hari-hari besar agama di Indonesia', ''),
('Penggalang Ramu', 'Spiritual', 3, 'Dapat menyebutkan agama-agama yang ada di Indonesia serta nama tempat ibadahnya', ''),
('Penggalang Ramu', 'Spiritual', 4, 'Memenuhi kecakapan keagamaan sesuai agama yang dianut', 'Islam: mandi wajib dan penyebabnya, sholat berjamaah, lima doa harian, dan lima surat pendek. Katolik: doa Rosario dan artinya, mengikuti Ekaristi hari Minggu dan menjadi putera/puteri altar, serta tiga lagu gerejani. Protestan: nyanyian Gereja, dua hikayat Alkitab, doa sederhana, dan hari raya Kristiani. Hindu: Tri Sandhya, para Maha Rsi, Sad Kahyangan, tokoh Mahabharata dan Ramayana, Tatwamasi, Catur Asrama, serta Yoga Asanas. Buddha: simbol altar Buddha, lagu Pancasila Buddhis, dan dana paramita.'),
('Penggalang Ramu', 'Emosional', 5, 'Dapat menjelaskan tentang emosi', ''),
('Penggalang Ramu', 'Emosional', 6, 'Dapat menyampaikan pendapat dengan baik dalam suatu pertemuan Pasukan Penggalang', ''),
('Penggalang Ramu', 'Sosial', 7, 'Dapat mengetahui dan menjelaskan manfaat penghijauan', ''),
('Penggalang Ramu', 'Sosial', 8, 'Dapat mengetahui dan memahami tentang hak perlindungan anak', ''),
('Penggalang Ramu', 'Sosial', 9, 'Ikut serta dalam perkemahan Penggalang minimal dua hari sesuai standar perkemahan', ''),
('Penggalang Ramu', 'Sosial', 10, 'Dapat menyebutkan tanda pengenal Gerakan Pramuka sesuai golongan dan tingkatannya', ''),
('Penggalang Ramu', 'Sosial', 11, 'Mengetahui nama ketua RT hingga lurah, camat, dan tokoh masyarakat setempat', ''),
('Penggalang Ramu', 'Sosial', 12, 'Dapat mengetahui dan menyebutkan Kode Kehormatan Pramuka Penggalang', ''),
('Penggalang Ramu', 'Sosial', 13, 'Rajin mengikuti latihan Pasukan Penggalang sekurang-kurangnya delapan kali berturut-turut', ''),
('Penggalang Ramu', 'Sosial', 14, 'Tahu tentang Salam Pramuka, Motto, dan arti Lambang Gerakan Pramuka', ''),
('Penggalang Ramu', 'Sosial', 15, 'Dapat menjelaskan sejarah, kiasan warna, serta cara menggunakan bendera Merah Putih', ''),
('Penggalang Ramu', 'Sosial', 16, 'Dapat menjelaskan dan menyanyikan Indonesia Raya dengan sikap benar serta menyanyikan dua lagu wajib nasional dan satu lagu daerah', ''),
('Penggalang Ramu', 'Sosial', 17, 'Dapat menjelaskan tentang Lambang Negara Republik Indonesia', ''),
('Penggalang Ramu', 'Sosial', 18, 'Dapat menggunakan Bahasa Indonesia yang baik dan benar', ''),
('Penggalang Ramu', 'Sosial', 19, 'Menabung secara rutin dan membayar iuran regu dari usaha sendiri', ''),
('Penggalang Ramu', 'Intelektual', 20, 'Dapat menyebutkan dan menjelaskan manfaat sedikitnya dua alat teknologi informasi modern', ''),
('Penggalang Ramu', 'Intelektual', 21, 'Dapat mengenal dan memilah sampah', ''),
('Penggalang Ramu', 'Intelektual', 22, 'Dapat menjelaskan teknik penjernihan air', ''),
('Penggalang Ramu', 'Intelektual', 23, 'Dapat membuat dan menggunakan simpul, ikatan, menyusuk tali, serta menyambung dua tongkat', 'Mencakup simpul mati, hidup, anyam, tiang, dan pangkal.'),
('Penggalang Ramu', 'Intelektual', 24, 'Dapat menjelaskan kompas serta menaksir tinggi dan lebar', ''),
('Penggalang Ramu', 'Intelektual', 25, 'Mengenal macam-macam sandi, isyarat Morse, dan semaphore', ''),
('Penggalang Ramu', 'Fisik', 26, 'Selalu berpakaian rapi serta memelihara kesehatan dan kebersihan diri dan lingkungan', ''),
('Penggalang Ramu', 'Fisik', 27, 'Dapat baris-berbaris', ''),
('Penggalang Ramu', 'Fisik', 28, 'Dapat menjelaskan tiga cabang olahraga dan melakukan dua cabang, salah satunya renang', ''),
('Penggalang Ramu', 'Fisik', 29, 'Mengetahui adanya perbedaan perkembangan fisik tubuh', ''),
('Penggalang Ramu', 'Fisik', 30, 'Melakukan aktivitas fisik setiap hari sedikitnya 30 menit', ''),

('Penggalang Rakit', 'Spiritual', 1, 'Mengikuti acara keagamaan sesuai agamanya', ''),
('Penggalang Rakit', 'Spiritual', 2, 'Membuat laporan singkat kegiatan keagamaan yang diikutinya', ''),
('Penggalang Rakit', 'Spiritual', 3, 'Dapat menjelaskan bentuk toleransi antarumat beragama di lingkungannya', ''),
('Penggalang Rakit', 'Spiritual', 4, 'Memenuhi kecakapan keagamaan tingkat Rakit sesuai agama yang dianut', 'Mencakup praktik ibadah, pemahaman ajaran, doa atau nyanyian keagamaan, peran aktif dalam kegiatan, serta kecakapan khusus menurut agama Islam, Katolik, Protestan, Hindu, atau Buddha sebagaimana dirinci dalam panduan Kwarnas.'),
('Penggalang Rakit', 'Emosional', 5, 'Dapat melaksanakan dan memimpin diskusi regu', ''),
('Penggalang Rakit', 'Emosional', 6, 'Dapat menyebutkan ciri-ciri mengendalikan emosi diri', ''),
('Penggalang Rakit', 'Sosial', 7, 'Melakukan penghijauan serta menanam dan merawat tanaman penghijauan', ''),
('Penggalang Rakit', 'Sosial', 8, 'Dapat menjelaskan tentang hak perlindungan anak', ''),
('Penggalang Rakit', 'Sosial', 9, 'Ikut serta dalam Lomba Tingkat dan lomba Pramuka Penggalang di gugus depan atau kwartir', ''),
('Penggalang Rakit', 'Sosial', 10, 'Dapat menyebutkan tanda pengenal pada pakaian seragam Pramuka', ''),
('Penggalang Rakit', 'Sosial', 11, 'Dapat membuat struktur pemerintahan dari tingkat kelurahan hingga RT di tempat tinggalnya', ''),
('Penggalang Rakit', 'Sosial', 12, 'Dapat menjelaskan nilai-nilai dalam Satya dan Darma Pramuka Penggalang', ''),
('Penggalang Rakit', 'Sosial', 13, 'Rajin mengikuti latihan Pasukan Penggalang sekurang-kurangnya sepuluh kali berturut-turut', ''),
('Penggalang Rakit', 'Sosial', 14, 'Dapat menjelaskan dan melaksanakan cara memberi Salam Pramuka', ''),
('Penggalang Rakit', 'Sosial', 15, 'Dapat menjelaskan sejarah bendera Merah Putih dan perlakuannya', 'Mengacu pada Undang-Undang Nomor 24 Tahun 2009.'),
('Penggalang Rakit', 'Sosial', 16, 'Dapat menjelaskan sejarah Lagu Kebangsaan Indonesia Raya dan perlakuannya', 'Mengacu pada Undang-Undang Nomor 24 Tahun 2009.'),
('Penggalang Rakit', 'Sosial', 17, 'Dapat menjelaskan Lambang Negara dan perlakuannya', 'Mengacu pada Undang-Undang Nomor 24 Tahun 2009.'),
('Penggalang Rakit', 'Sosial', 18, 'Berbahasa Indonesia dengan baik dan benar serta membuat laporan tertulis dari pertemuan', ''),
('Penggalang Rakit', 'Sosial', 19, 'Memiliki tabungan pribadi dan aktif menabung secara rutin', ''),
('Penggalang Rakit', 'Intelektual', 20, 'Dapat mengoperasikan dan merawat salah satu teknologi informasi', ''),
('Penggalang Rakit', 'Intelektual', 21, 'Dapat mengolah sampah dan mempraktikkan pengomposan', ''),
('Penggalang Rakit', 'Intelektual', 22, 'Dapat melakukan penjernihan air secara sederhana', ''),
('Penggalang Rakit', 'Intelektual', 23, 'Dapat membuat beberapa jenis pioneering', 'Contoh: rak piring, meja makan, tiang jemuran, dan menara kaki tiga.'),
('Penggalang Rakit', 'Intelektual', 24, 'Dapat menggunakan kompas, membuat peta pita, serta menaksir kecepatan arus dan kedalaman', ''),
('Penggalang Rakit', 'Intelektual', 25, 'Dapat membuat dan menerjemahkan sandi serta menerima berita dengan Morse dan semaphore', ''),
('Penggalang Rakit', 'Fisik', 26, 'Selalu berpakaian rapi serta memelihara kesehatan dan kebersihan diri dan lingkungan', ''),
('Penggalang Rakit', 'Fisik', 27, 'Dapat memimpin regunya untuk baris-berbaris', ''),
('Penggalang Rakit', 'Fisik', 28, 'Tahu peraturan tiga cabang olahraga dan dapat melakukan salah satunya', ''),
('Penggalang Rakit', 'Fisik', 29, 'Mengetahui perubahan fisik dirinya dan memahami norma pergaulan', ''),
('Penggalang Rakit', 'Fisik', 30, 'Dapat menunjukkan jadwal kegiatan fisik dan gerakan tubuh setiap hari', ''),

('Penggalang Terap', 'Spiritual', 1, 'Taat beribadah sesuai agama dan mengajak orang lain untuk beribadah', ''),
('Penggalang Terap', 'Spiritual', 2, 'Berperan aktif dalam penyelenggaraan kegiatan keagamaan di Gerakan Pramuka maupun masyarakat', ''),
('Penggalang Terap', 'Spiritual', 3, 'Dapat mengajak orang lain berperilaku toleran antarumat beragama', ''),
('Penggalang Terap', 'Spiritual', 4, 'Memenuhi kecakapan keagamaan tingkat Terap sesuai agama yang dianut', 'Mencakup kemampuan memimpin ibadah atau doa, pemahaman ajaran dan struktur keagamaan, praktik keagamaan, serta kecakapan khusus menurut agama Islam, Katolik, Protestan, Hindu, atau Buddha sebagaimana dirinci dalam panduan Kwarnas.'),
('Penggalang Terap', 'Emosional', 5, 'Dapat mengendalikan emosi teman sebaya', ''),
('Penggalang Terap', 'Emosional', 6, 'Dapat memimpin pertemuan Pasukan Penggalang', ''),
('Penggalang Terap', 'Sosial', 7, 'Mengajak teman atau regunya melakukan dan memelihara penghijauan', ''),
('Penggalang Terap', 'Sosial', 8, 'Dapat menyosialisasikan hak perlindungan anak kepada teman sebaya', ''),
('Penggalang Terap', 'Sosial', 9, 'Telah ikut serta dalam Jambore, Lomba Tingkat, atau perkemahan lainnya', ''),
('Penggalang Terap', 'Sosial', 10, 'Dapat menjelaskan tanda-tanda pengenal Gerakan Pramuka', ''),
('Penggalang Terap', 'Sosial', 11, 'Dapat menjelaskan tugas dan fungsi kepala desa atau lurah, camat, serta bupati atau wali kota', ''),
('Penggalang Terap', 'Sosial', 12, 'Mengajak regu dan pasukan mengamalkan Kode Kehormatan Pramuka Penggalang', ''),
('Penggalang Terap', 'Sosial', 13, 'Rajin mengikuti latihan Pasukan Penggalang sekurang-kurangnya dua belas kali berturut-turut', ''),
('Penggalang Terap', 'Sosial', 14, 'Dapat menjelaskan dan menggunakan Salam Pramuka', ''),
('Penggalang Terap', 'Sosial', 15, 'Dapat mengibarkan dan menurunkan bendera Merah Putih pada upacara hari besar nasional', ''),
('Penggalang Terap', 'Sosial', 16, 'Dapat memimpin Indonesia Raya serta menyanyikan lagu wajib dan lagu daerah', 'Memimpin Indonesia Raya dalam upacara, menyanyikan empat lagu wajib, tiga lagu daerah tempat tinggal, dan tiga lagu daerah lainnya.'),
('Penggalang Terap', 'Sosial', 17, 'Dapat menjelaskan Lambang Negara Republik Indonesia di depan pasukan atau teman sebaya', ''),
('Penggalang Terap', 'Sosial', 18, 'Dapat menggunakan Bahasa Indonesia yang baik dan benar dalam pertemuan resmi', ''),
('Penggalang Terap', 'Sosial', 19, 'Dapat menjelaskan manfaat menabung dan iuran serta mengajak regu gemar menabung', ''),
('Penggalang Terap', 'Intelektual', 20, 'Dapat mengajarkan penggunaan sedikitnya dua teknologi informasi kepada teman sebaya', ''),
('Penggalang Terap', 'Intelektual', 21, 'Ikut menyosialisasikan cara pengolahan sampah', ''),
('Penggalang Terap', 'Intelektual', 22, 'Dapat menyosialisasikan cara penjernihan air', ''),
('Penggalang Terap', 'Intelektual', 23, 'Dapat membuat pioneering jembatan dan menara pandang sederhana', ''),
('Penggalang Terap', 'Intelektual', 24, 'Dapat membuat peta perjalanan dan peta lapangan serta menjelaskan rumus penaksiran', 'Mencakup penaksiran tinggi, lebar, kecepatan, dan kedalaman.'),
('Penggalang Terap', 'Intelektual', 25, 'Dapat mengirim dan menerima berita dengan Morse dan semaphore serta membuat sandi kreasi pribadi', ''),
('Penggalang Terap', 'Fisik', 26, 'Selalu berpakaian rapi dan menjadi teladan dalam kesehatan serta kebersihan diri dan lingkungan', ''),
('Penggalang Terap', 'Fisik', 27, 'Dapat memimpin dan melatih baris-berbaris di pasukannya', ''),
('Penggalang Terap', 'Fisik', 28, 'Dapat melakukan olahraga beregu dan tiga cabang olahraga beserta peraturannya, termasuk renang', ''),
('Penggalang Terap', 'Fisik', 29, 'Dapat mengatasi perubahan perkembangan fisik tubuh', ''),
('Penggalang Terap', 'Fisik', 30, 'Dapat menjelaskan manfaat dan melakukan aktivitas fisik setiap hari sedikitnya 45 menit', '')
on conflict (level, item_number) do update set
  category = excluded.category,
  title = excluded.title,
  description = excluded.description;
